In [1]:
import numpy as np
from numpy import linalg as la

In [43]:
zero = np.array([1,0])

one = np.array([0,1])

Z = np.outer(zero,zero) - np.outer(one,one)

I = np.eye(2)

# print(np.kron(I,Z))

def Z_i(i):
    if i == 0:
        a = np.kron(Z,I)
        b = np.kron(a,I)
        c = np.kron(b,I)
        d = np.kron(c,I)
        return d
    if i == 1:
        a = np.kron(I,Z)
        b = np.kron(a,I)
        c = np.kron(b,I)
        d = np.kron(c,I)
        return d
    if i == 2:
        a = np.kron(I,I)
        b = np.kron(a,Z)
        c = np.kron(b,I)
        d = np.kron(c,I)
        return d
    if i == 3:
        a = np.kron(I,I)
        b = np.kron(a,I)
        c = np.kron(b,Z)
        d = np.kron(c,I)
        return d
    if i == 4:
        a = np.kron(I,I)
        b = np.kron(a,I)
        c = np.kron(b,I)
        d = np.kron(c,Z)
        return d
print(Z_i(2))

[[ 1.  0.  0. ...  0.  0.  0.]
 [ 0.  1.  0. ...  0.  0.  0.]
 [ 0.  0.  1. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ... -1. -0. -0.]
 [ 0.  0.  0. ... -0. -1. -0.]
 [ 0.  0.  0. ... -0. -0. -1.]]


In [76]:
la.eigh(a)[1].shape

(32, 32)

In [77]:
a = np.kron(I,I)
b = np.kron(a,Z)
c = np.kron(b,I)
d = np.kron(c,I)

d

array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ..., -1., -0., -0.],
       [ 0.,  0.,  0., ..., -0., -1., -0.],
       [ 0.,  0.,  0., ..., -0., -0., -1.]])

In [78]:
# a = np.kron(I,I)

# for x in range(3):
#     if x == 2:
#         a = np.kron(a,Z)
#     else:
#         a = np.kron(a,I)

# print(a.shape)

In [91]:
a = np.kron(np.kron(np.kron(np.kron(I,I),I),I),Z)
a

array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0., -1.,  0., ..., -0.,  0., -0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       ...,
       [ 0., -0.,  0., ..., -1.,  0., -0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0., -0.,  0., ..., -0.,  0., -1.]])

In [96]:
for x,y in zip(Z_i(4),a):
    for i,j in zip(x,y):
        if i != j:
            print('Something went wrong!')
print('done!')

done!


In [95]:
count = 0

for x in la.eigh(Z_i(0))[1]:
    print(x)
    count += 1
    print(count)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
1
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
2
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
3
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
4
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
5
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
6
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
7
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
 0. 0. 0. 0. 0. 0. 0. 0.]
8
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 1. 0. 0. 0. 0. 0. 0. 0.]
9
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 1. 0. 0. 0. 0.

In [103]:
la.eigh(np.matmul(Z_i(0),Z_i(1)))[1].shape

(32, 32)